name: Javascript CI
on : [push]

jobs : 
  test :
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v1
      - name: use Node.js 12.x
        uses: actions/setup-node@v1
        with: 
          node-version: "12.x"
      - name: npm install, test, coverage
        run : |
          npm install
          npm test
          npm run codecov
        env : 
          CI: true
          CODECOV_TOKEN: 13fae502-88d5-4d79-92f8-86676f7979ae